import fs from 'node:fs';
const path = 'apps/web/src/main.tsx';
let source = fs.readFileSync(path, 'utf8');
source = source.replace('React, { useMemo, type ReactNode }', 'React, { type ReactNode }');
const importsStart = source.indexOf('import { ConvexReactClient');
const importsEnd = source.indexOf('import { tokens }');
source = source.slice(0, importsStart) + 'import { clientConfiguration } from "domain/core";\n' + source.slice(importsEnd);
const liveStart = source.indexOf('  const client = new ConvexReactClient');
const liveEnd = source.indexOf('} else if (import.meta.env.DEV', liveStart);
source = source.slice(0, liveStart) + '  const { createLiveApp } = await import("./live-app");\n  render(createLiveApp(configuration.url, configuration.site));\n' + source.slice(liveEnd);
fs.writeFileSync(path, source);
