import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fafafa',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
  },
  loadingText: {
    color: '#737373',
    fontSize: 16,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 100,
    gap: 16,
  },
  versesContainer: {
    gap: 12,
  },
  monthlyVerseCard: {
    backgroundColor: '#fefce8',
    borderWidth: 1,
    borderColor: '#fde047',
    borderRadius: 12,
    padding: 20,
  },
  weeklyVerseCard: {
    backgroundColor: '#f5f5f5',
    borderWidth: 1,
    borderColor: '#e5e5e5',
    borderRadius: 12,
    padding: 20,
  },
  verseLabel: {
    fontSize: 12,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    color: '#713f12',
    marginBottom: 8,
  },
  verseText: {
    fontSize: 16,
    fontFamily: 'Georgia',
    color: '#713f12',
    lineHeight: 24,
  },
  dateContainer: {
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e5e5',
  },
  dateText: {
    fontSize: 14,
    color: '#737373',
    textAlign: 'center',
  },
  emptyState: {
    backgroundColor: '#fafafa',
    borderWidth: 1,
    borderColor: '#e5e5e5',
    borderRadius: 12,
    padding: 32,
    alignItems: 'center',
  },
  emptyText: {
    fontSize: 16,
    color: '#737373',
    textAlign: 'center',
  },
  scriptureCard: {
    backgroundColor: '#fafafa',
    borderLeftWidth: 4,
    borderLeftColor: '#16a34a',
    borderRadius: 8,
    padding: 20,
  },
  scriptureText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#171717',
    lineHeight: 26,
  },
  reflectionCard: {
    gap: 12,
  },
  reflectionText: {
    fontSize: 16,
    color: '#404040',
    lineHeight: 26,
  },
  audioCard: {
    backgroundColor: '#f5f5f5',
    borderWidth: 1,
    borderColor: '#e5e5e5',
    borderRadius: 12,
    padding: 16,
  },
  audioControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  playButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#16a34a',
    justifyContent: 'center',
    alignItems: 'center',
  },
  playButtonPlaying: {
    backgroundColor: '#15803d',
  },
  playButtonText: {
    fontSize: 20,
  },
  audioLabel: {
    fontSize: 16,
    color: '#171717',
    fontWeight: '500',
  },
  prayerCard: {
    backgroundColor: '#fdf4ff',
    borderWidth: 1,
    borderColor: '#e879f9',
    borderRadius: 12,
    padding: 20,
  },
  prayerLabel: {
    fontSize: 12,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    color: '#701a75',
    marginBottom: 8,
  },
  prayerText: {
    fontSize: 16,
    color: '#701a75',
    lineHeight: 24,
  },
  joinContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
    gap: 16,
  },
  joinTitle: {
    fontSize: 24,
    fontWeight: '600',
    color: '#171717',
  },
  joinInput: {
    width: '100%',
    maxWidth: 300,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#e5e5e5',
    borderRadius: 12,
    padding: 16,
    fontSize: 18,
    textAlign: 'center',
    letterSpacing: 2,
  },
  joinButton: {
    backgroundColor: '#16a34a',
    paddingHorizontal: 32,
    paddingVertical: 14,
    borderRadius: 12,
    marginTop: 8,
  },
  joinButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  scriptureLabel: {
    fontSize: 12,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    color: '#713f12',
    marginBottom: 8,
  },
  messagesSection: {
    marginTop: 8,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#171717',
    marginBottom: 12,
  },
  messageCard: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#e5e5e5',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
  },
  messageText: {
    fontSize: 16,
    color: '#171717',
    lineHeight: 24,
    marginBottom: 8,
  },
  messageTime: {
    fontSize: 12,
    color: '#737373',
    textAlign: 'right',
  },
  emptyMessages: {
    fontSize: 16,
    color: '#737373',
    textAlign: 'center',
    paddingVertical: 32,
  },
  composerContainer: {
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: '#e5e5e5',
    backgroundColor: '#fafafa',
  },
  composerInner: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 8,
  },
  composerInput: {
    flex: 1,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#e5e5e5',
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 10,
    fontSize: 16,
    maxHeight: 120,
  },
  composerButton: {
    backgroundColor: '#16a34a',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 24,
  },
  composerButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
});