name: Sync to Org Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Push to org repo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Adicionar remoto usando PAT e executar push
        env:
          TOKEN: ${{ secrets.LEVEL_REPO }}  # Seu PAT com escopo public_repo
        run: |
          git remote add org https://x-access-token:${TOKEN}@github.com/zapf-coorp/devotio-app.git
          git push --force org main
